-- Run this in Supabase SQL Editor
-- Creates tables for admin dashboard: clips + schedule management

-- Best Clips table
CREATE TABLE IF NOT EXISTS clips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL DEFAULT '',
  video_url TEXT NOT NULL DEFAULT '',
  thumbnail_url TEXT DEFAULT '',
  kick_link TEXT DEFAULT '',
  featured BOOLEAN DEFAULT false,
  active BOOLEAN DEFAULT true,
  position INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Schedule table
CREATE TABLE IF NOT EXISTS schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_of_week INT NOT NULL UNIQUE,
  label TEXT NOT NULL DEFAULT '',
  time_text TEXT DEFAULT '10:00 AM',
  timezone TEXT DEFAULT 'ET',
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default schedule rows (one per day)
INSERT INTO schedule (day_of_week, label, time_text, timezone, active)
VALUES
  (0, 'Sunday', '10:00 AM', 'ET', true),
  (1, 'Monday', '10:00 AM', 'ET', true),
  (2, 'Tuesday', '10:00 AM', 'ET', true),
  (3, 'Wednesday', '10:00 AM', 'ET', true),
  (4, 'Thursday', '10:00 AM', 'ET', true),
  (5, 'Friday', '10:00 AM', 'ET', true),
  (6, 'Saturday', '10:00 AM', 'ET', true)
ON CONFLICT (day_of_week) DO NOTHING;

-- Enable realtime for both tables
ALTER PUBLICATION supabase_realtime ADD TABLE clips;
ALTER PUBLICATION supabase_realtime ADD TABLE schedule;

-- Create storage bucket for clips (run in Supabase Storage section)
-- Bucket name: clips
-- Public bucket: true
-- RLS: Allow public select, allow insert/update/delete for all (since auth is Discord-based)
