-- Run this in Supabase SQL Editor
-- Creates schedule table for admin dashboard stream schedule management
-- No seed data: admins toggle days on/off and set times via the dashboard.

CREATE TABLE IF NOT EXISTS schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_of_week INT NOT NULL UNIQUE,
  label TEXT NOT NULL DEFAULT '',
  time_text TEXT DEFAULT '10:00 AM',
  timezone TEXT DEFAULT 'ET',
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER PUBLICATION supabase_realtime ADD TABLE schedule;
